name: llm
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - transformers
  - pip:
    - transformers>=4.31
    - scikit-learn
    - tokenizers>=0.13.3
    - accelerate
    - openai
    - tiktoken
    - bitsandbytes
    - tenacity
    - safetensors
